# ======================================================================================
#  __    ____  __  __  ____  ___
# (  )  (_  _)(  \/  )( ___)/ __)
#  )(__  _)(_  )    (  )__) \__ \
# (____)(____)(_/\/\_)(____)(___/
#
#  This file is part of the Limes open source library and is licensed under the terms of the GNU Public License.
#
#  Commercial licenses are available; contact the maintainers at ben.the.vining@gmail.com to inquire for details.
#
# ======================================================================================

version: 2

updates:

- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: chore(deps) [skip ci]
    include: scope
  reviewers:
  - benthevining

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: chore(deps) [skip ci]
    include: scope
  reviewers:
  - benthevining
