# ======================================================================================
#  __    ____  __  __  ____  ___
# (  )  (_  _)(  \/  )( ___)/ __)
#  )(__  _)(_  )    (  )__) \__ \
# (____)(____)(_/\/\_)(____)(___/
#
#  This file is part of the Limes open source library and is licensed under the terms of the GNU Public License.
#
#  Commercial licenses are available; contact the maintainers at ben.the.vining@gmail.com to inquire for details.
#
# ======================================================================================

# This workflow builds the docs and commits them to the docs branch

name: Build docs

run-name: Build docs (${{ github.actor }})

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: write

env:
  CMAKE_PRESET: clang

jobs:

  Build_docs:

    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    name: Build docs

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:

    - name: Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c   # pin@v3
      with:
        fetch-depth: 1

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install dependencies
      run: sudo apt-get install --yes doxygen graphviz

    - name: Configure CMake
      run: cmake --preset ${{ env.CMAKE_PRESET }}

    - name: Build docs
      run: cmake --build --preset ${{ env.CMAKE_PRESET }} --target lfilesystem_docs

    - name: Clone docs branch
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c   # pin@v3
      with:
        ref: docs
        path: tmp
        fetch-depth: 0

    - name: Remove everything currently in docs branch
      run: rm -rf *
      working-directory: tmp

    - name: Copy generated docs to docs branch
      run: cp -a /doc/html/. /tmp/

    - name: Create empty nojekyll file
      run: touch tmp/.nojekyll

    - name: Commit & push changes to docs branch
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: Updating docs (built from commit ${{ github.sha }})
        branch: docs
        force: true
        directory: tmp
